services:
  mysql:
    image: mysql:8.0
    container_name: recettes_db
    restart: always
    environment:
      MYSQL_DATABASE: recettes_db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3308:3306"
    volumes:
      - recettes_data:/var/lib/mysql
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  recettes_data:
